name: Tests

on:
  push:
    branches:
      - master
      - stable
  pull_request:
    branches:
      - master

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install
      - name: Run static code inspections
        run: pre-commit run --all-files

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install flake8
        run: pip install flake8==3.8.3 flake8-bugbear==20.1.4
      - name: Run static code inspections
        run: flake8 --max-line-length 140 --extend-ignore E203,B306 .

  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install torch==1.8.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install -e .[visdom,torch,tests]
      - name: Run tests
        run: python -m pytest --cov=tiger tests/

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build documentation
        uses: docker/build-push-action@v2
        with:
          target: docs_builder
          tags: tiger:docs
          push: false
